version: '2'

services:
    wildfly:
        build: ../
        container_name: front-app42
        restart: always
        ports:
            - "8080:8080"
        environment:
            - IMAGE_STORE_PATH=/image/
        volumes:
            - image-data:/image/
        links:
            - redis:redis

    redis:
        image: redis
        container_name: redis42
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

    php-redis-admin:
        image: faktiva/php-redis-admin
        container_name: phpredisadmin42
        restart: always
        ports:
            - "8090:80"
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        depends_on:
            - redis

    apache-server:
        image: httpd
        container_name: apache42
        restart: always
        ports:
            - "8070:80"
        volumes:
            - image-data:/usr/local/apache2/htdocs/

volumes:
  image-data:
  redis-data:
